AWSTemplateFormatVersion: '2010-09-09'
Description: Instance Scheduler basic resources

Resources:
  ConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: InstanceSchedulerConfigTable
      AttributeDefinitions:
        - AttributeName: type
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: type
          KeyType: HASH
        - AttributeName: name
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  ConfigurationTable:
    Description: DynamoDB Configuration table ARN
    Value: !GetAtt ConfigTable.Arn
